import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from "react";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
const ReactPlayer = dynamic(() => import("react-player"), { ssr: false });
import logo from './main.png';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const [url, setUrl] = useState("");
	const [selectedVideo, setSelectedVideo] = useState(null)

    const videos = 
	[
        {
            name: 'Video 1',
            thumbnail: 'https://example.com/video1-thumbnail.jpg',
            videoUrl: 'https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8'
        },
        {
            name: 'Video 2',
            thumbnail: 'https://example.com/video2-thumbnail.jpg',
            videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.mp4/.m3u8'
		},
		        {
            name: 'Video 1',
            thumbnail: 'https://example.com/video1-thumbnail.jpg',
            videoUrl: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8'
        },
        {
            name: 'Video 2',
            thumbnail: 'https://example.com/video2-thumbnail.jpg',
            videoUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8'
		},
	]


	const handleUrlChange = (event: React.ChangeEvent<HTMLInputElement>) => {
	  setUrl(event.target.value);
	};

	const sendRequest = (event: any) => {
		console.log(url)
	}

	function handleVideoClick(video: string){
		console.log(video);
	}

	function changeFirstParam(someParam: string) {
		console.log(someParam)
	}

	function changeUrl(newUrl: string){
		setUrl(newUrl)
	}

	function changeSecondParam(someParam: string) {
		console.log(someParam)
	}

	const listItems = videos.map(video =>
		<li key={video.name}>
						<button
						className={styles.buttoncard}
						type="button"
						onClick={() => changeUrl(video.videoUrl)}
						>
						<h2 className={inter.className}>
						{video.name} <span>-&gt;</span>
						</h2>
						<img src={'https://picsum.photos/200/300/?blur'} height='200px' width='100px' />
						<p className={inter.className}>
						Find in-depth information about Next.js features and&nbsp;API.
						</p>
						</button>
		</li>
	  );
	const chooseMovie = (event: any) => {
		console.log(url)
	}

	const handleApiRequest = () => {
	  console.log(url)
	  fetch("https://api.example.com/my-endpoint", {
		method: "POST",
		body: JSON.stringify({ url }),
		headers: {
		  "Content-Type": "application/json"
		}
	  })
		.then(response => response.json())
		.then(data => console.log(data))
		.catch(error => console.error(error));
	};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <button className={styles.button} type="button" onClick={sendRequest}></button>
      <main className={styles.main}>

			<div>
				<ul>{listItems}</ul>
			</div>
			<div>
					<div className={styles.gridtop}>

						<div className={styles.searchbar}>
							<input
							type="text"
							className={styles.input}
							placeholder="Введите ссылку на стрим или видео"
							value={url}
							onChange={handleUrlChange}
							/>
						</div>

						<button className={styles.button} type="button" onClick={sendRequest}>
						Загрузить
						</button>

					</div>

					<div className={styles.gridmiddle}>

						<button
						className={styles.buttoncard}
						type="button"
						onClick={() => changeFirstParam('мужской')}
						>
									<h2 className={inter.className}>
									Мужской голос
									</h2>
						</button>

						<button
						className={styles.buttoncard}
						type="button"
						onClick={() => changeSecondParam('женский')}
						>
									<h2 className={inter.className}>
									Мужской голос
									</h2>
						</button>

					</div>
				<div className={styles.gridvideo}>
				<ReactPlayer 
				playing 
				url={url}
				width='100%'
				height='100%'
				controls={true}
				/>
				</div>
			</div>

      </main>
    </>
  )
}
